// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using system_copsoq_api.Data;

#nullable disable

namespace system_copsoq_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20251029173606_AddDisparoAndRespostaTables")]
    partial class AddDisparoAndRespostaTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("system_copsoq_api.Models.Disparo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("datetime2");

                    b.Property<int>("FuncionarioID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("int");

                    b.Property<bool>("Respondido")
                        .HasColumnType("bit");

                    b.Property<Guid>("TokenAcesso")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ID");

                    b.HasIndex("FuncionarioID");

                    b.HasIndex("QuestionarioID");

                    b.HasIndex("TokenAcesso")
                        .IsUnique();

                    b.ToTable("Disparos");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Empresa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("bit");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SetorAtuacao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Dimensao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("NomeIndicador")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Ordem")
                        .HasColumnType("int");

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("int");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("QuestionarioID");

                    b.ToTable("Dimensoes");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Pergunta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DimensaoID")
                        .HasColumnType("int");

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("int");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("DimensaoID");

                    b.HasIndex("QuestionarioID");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Questionario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoConsentimento")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TextoIntroducao")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Questionarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.QuestionarioSetorAplicavel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("int");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("QuestionarioID");

                    b.ToTable("QuestionarioSetoresAplicaveis");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Funcionario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.RespostaFuncionario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("DisparoID")
                        .HasColumnType("int");

                    b.Property<int>("PerguntaID")
                        .HasColumnType("int");

                    b.Property<int>("ValorResposta")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("DisparoID");

                    b.HasIndex("PerguntaID");

                    b.ToTable("RespostasFuncionarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("EmpresaID")
                        .HasColumnType("int");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Disparo", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Funcionario", "Funcionario")
                        .WithMany("Disparos")
                        .HasForeignKey("FuncionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany()
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Dimensao", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany("Dimensoes")
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Pergunta", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Formularios.Dimensao", "Dimensao")
                        .WithMany("Perguntas")
                        .HasForeignKey("DimensaoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany("Perguntas")
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensao");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.QuestionarioSetorAplicavel", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany("SetoresAplicaveis")
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Funcionario", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Empresa", "Empresa")
                        .WithMany("Funcionarios")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("system_copsoq_api.Models.RespostaFuncionario", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Disparo", "Disparo")
                        .WithMany("Respostas")
                        .HasForeignKey("DisparoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("system_copsoq_api.Models.Formularios.Pergunta", "Pergunta")
                        .WithMany("Respostas")
                        .HasForeignKey("PerguntaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disparo");

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("system_copsoq_api.Models.User", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Disparo", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Empresa", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Dimensao", b =>
                {
                    b.Navigation("Perguntas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Pergunta", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Questionario", b =>
                {
                    b.Navigation("Dimensoes");

                    b.Navigation("Perguntas");

                    b.Navigation("SetoresAplicaveis");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Funcionario", b =>
                {
                    b.Navigation("Disparos");
                });
#pragma warning restore 612, 618
        }
    }
}
