// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using system_copsoq_api.Data;

#nullable disable

namespace system_copsoq_api.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("system_copsoq_api.Models.Disparo.Disparo", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataEnvio")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataResposta")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FuncionarioID")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("integer");

                    b.Property<bool>("Respondido")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TokenAcesso")
                        .HasColumnType("uuid");

                    b.HasKey("ID");

                    b.HasIndex("FuncionarioID");

                    b.HasIndex("QuestionarioID");

                    b.HasIndex("TokenAcesso")
                        .IsUnique();

                    b.ToTable("Disparos");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Disparo.RespostaFuncionario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DisparoID")
                        .HasColumnType("integer");

                    b.Property<int>("PerguntaID")
                        .HasColumnType("integer");

                    b.Property<string>("TextoResposta")
                        .HasColumnType("text");

                    b.Property<int?>("ValorResposta")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("DisparoID");

                    b.HasIndex("PerguntaID");

                    b.ToTable("RespostasFuncionarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Empresa", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("NomeEmpresa")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NomeResponsavel")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SetorAtuacao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Dimensao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("NomeIndicador")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("QuestionarioID");

                    b.ToTable("Dimensoes");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.OpcaoResposta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Valor")
                        .HasColumnType("integer");

                    b.HasKey("ID");

                    b.HasIndex("QuestionarioID");

                    b.ToTable("OpcoesResposta");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Pergunta", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("DimensaoID")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("DimensaoID");

                    b.HasIndex("QuestionarioID");

                    b.ToTable("Perguntas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Questionario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextoConsentimento")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TextoIntroducao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.ToTable("Questionarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.QuestionarioSetorAplicavel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<int>("QuestionarioID")
                        .HasColumnType("integer");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("QuestionarioID");

                    b.ToTable("QuestionarioSetoresAplicaveis");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Funcionario", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Cargo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("integer");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Setor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Funcionarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Planos.Acao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime?>("DataConclusao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Justificativa")
                        .HasColumnType("text");

                    b.Property<int>("PlanoDeAcaoID")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("Prazo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("PlanoDeAcaoID");

                    b.ToTable("Acoes");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Planos.PlanoDeAcao", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("EmpresaID")
                        .HasColumnType("integer");

                    b.Property<bool>("IsAtivo")
                        .HasColumnType("boolean");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("PlanosDeAcao");
                });

            modelBuilder.Entity("system_copsoq_api.Models.User", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ID"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("EmpresaID")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SenhaHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ID");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("EmpresaID");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Disparo.Disparo", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Funcionario", "Funcionario")
                        .WithMany("Disparos")
                        .HasForeignKey("FuncionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany()
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Funcionario");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Disparo.RespostaFuncionario", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Disparo.Disparo", "Disparo")
                        .WithMany("Respostas")
                        .HasForeignKey("DisparoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("system_copsoq_api.Models.Formularios.Pergunta", "Pergunta")
                        .WithMany("Respostas")
                        .HasForeignKey("PerguntaID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Disparo");

                    b.Navigation("Pergunta");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Dimensao", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany("Dimensoes")
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.OpcaoResposta", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany("OpcoesResposta")
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Pergunta", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Formularios.Dimensao", "Dimensao")
                        .WithMany("Perguntas")
                        .HasForeignKey("DimensaoID")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany("Perguntas")
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dimensao");

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.QuestionarioSetorAplicavel", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Formularios.Questionario", "Questionario")
                        .WithMany("SetoresAplicaveis")
                        .HasForeignKey("QuestionarioID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Questionario");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Funcionario", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Empresa", "Empresa")
                        .WithMany("Funcionarios")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Planos.Acao", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Planos.PlanoDeAcao", "PlanoDeAcao")
                        .WithMany("Acoes")
                        .HasForeignKey("PlanoDeAcaoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PlanoDeAcao");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Planos.PlanoDeAcao", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Empresa", "Empresa")
                        .WithMany("PlanosDeAcao")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("system_copsoq_api.Models.User", b =>
                {
                    b.HasOne("system_copsoq_api.Models.Empresa", "Empresa")
                        .WithMany("Usuarios")
                        .HasForeignKey("EmpresaID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Empresa");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Disparo.Disparo", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Empresa", b =>
                {
                    b.Navigation("Funcionarios");

                    b.Navigation("PlanosDeAcao");

                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Dimensao", b =>
                {
                    b.Navigation("Perguntas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Pergunta", b =>
                {
                    b.Navigation("Respostas");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Formularios.Questionario", b =>
                {
                    b.Navigation("Dimensoes");

                    b.Navigation("OpcoesResposta");

                    b.Navigation("Perguntas");

                    b.Navigation("SetoresAplicaveis");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Funcionario", b =>
                {
                    b.Navigation("Disparos");
                });

            modelBuilder.Entity("system_copsoq_api.Models.Planos.PlanoDeAcao", b =>
                {
                    b.Navigation("Acoes");
                });
#pragma warning restore 612, 618
        }
    }
}
